name: Test Branch Input

on:
  workflow_dispatch:
    inputs:
      branch:
        default: 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch
        run: echo "Branch is ${{ github.event.inputs.branch }}"
